texts = {
    "English": {
        "title": "Crypto Chart",
        "subtitle": "Real-time cryptocurrency chart with technical indicators",
        "language": "Language",
        "theme": "Theme",
        "dark": "Dark",
        "light": "Light",
        "chart_settings": "Chart Settings",
        "show_grid": "Show Grid",
        "show_crosshair": "Show Crosshair",
        "timezone": "Timezone",
        "select_coin": "Select Coin",
        "select_timeframe": "Select Timeframe",
        "indicators": "Indicators",
        "ma": "Moving Averages",
        "ma_settings": "MA Settings",
        "ma_period": "Period",
        "macd": "MACD",
        "macd_settings": "MACD Settings",
        "macd_fast": "Fast Period",
        "macd_slow": "Slow Period",
        "macd_signal": "Signal Period",
        "rsi": "RSI",
        "rsi_settings": "RSI Settings",
        "rsi_period": "Period",
        "ichimoku": "Ichimoku Cloud",
        "ichimoku_settings": "Ichimoku Settings",
        "ichimoku_tenkan": "Tenkan Period",
        "ichimoku_kijun": "Kijun Period",
        "ichimoku_senkou": "Senkou Period",
        "zoom_in": "Zoom In",
        "zoom_out": "Zoom Out",
        "update": "Update",
        "current_price": "Current Price",
        "price_change": "Price Change",
        "volume": "24h Volume",
        "market_cap": "Market Cap",
        "error_no_data": "No data available",
        "support_levels": "Support Levels",
        "resistance_levels": "Resistance Levels",
        "strength": "Strength",
        "price_label": "Price",
        "change_label": "Change",
        "volume_label": "Volume",
        "market_cap_label": "Market Cap",
        "pan_left": "← Pan Left",
        "pan_right": "Pan Right →"
    },
    "Persian": {
        "title": "نمودار ارز دیجیتال",
        "subtitle": "نمودار ارز دیجیتال با اندیکاتورهای تکنیکال",
        "language": "زبان",
        "theme": "تم",
        "dark": "تیره",
        "light": "روشن",
        "chart_settings": "تنظیمات نمودار",
        "show_grid": "نمایش خطوط شبکه",
        "show_crosshair": "نمایش خطوط راهنما",
        "timezone": "منطقه زمانی",
        "select_coin": "انتخاب ارز",
        "select_timeframe": "انتخاب بازه زمانی",
        "indicators": "اندیکاتورها",
        "ma": "میانگین متحرک",
        "ma_settings": "تنظیمات میانگین متحرک",
        "ma_period": "دوره",
        "macd": "MACD",
        "macd_settings": "تنظیمات MACD",
        "macd_fast": "دوره سریع",
        "macd_slow": "دوره کند",
        "macd_signal": "دوره سیگنال",
        "rsi": "RSI",
        "rsi_settings": "تنظیمات RSI",
        "rsi_period": "دوره",
        "ichimoku": "ابر ایچیموکو",
        "ichimoku_settings": "تنظیمات ایچیموکو",
        "ichimoku_tenkan": "دوره تنکان",
        "ichimoku_kijun": "دوره کیجون",
        "ichimoku_senkou": "دوره سنکو",
        "zoom_in": "بزرگنمایی",
        "zoom_out": "کوچک‌نمایی",
        "update": "به‌روزرسانی",
        "current_price": "قیمت فعلی",
        "price_change": "تغییر قیمت",
        "volume": "حجم ۲۴ ساعت",
        "market_cap": "ارزش بازار",
        "error_no_data": "داده‌ای موجود نیست",
        "support_levels": "سطوح حمایت",
        "resistance_levels": "سطوح مقاومت",
        "strength": "قدرت",
        "price_label": "قیمت",
        "change_label": "تغییر",
        "volume_label": "حجم",
        "market_cap_label": "ارزش بازار",
        "pan_left": "← حرکت به چپ",
        "pan_right": "حرکت به راست →"
    },
    "German": {
        "title": "Krypto-Chart",
        "subtitle": "Echtzeit-Kryptowährungs-Chart mit technischen Indikatoren",
        "language": "Sprache",
        "theme": "Thema",
        "dark": "Dunkel",
        "light": "Hell",
        "chart_settings": "Chart-Einstellungen",
        "show_grid": "Raster anzeigen",
        "show_crosshair": "Fadenkreuz anzeigen",
        "timezone": "Zeitzone",
        "select_coin": "Coin auswählen",
        "select_timeframe": "Zeitrahmen auswählen",
        "indicators": "Indikatoren",
        "ma": "Gleitende Durchschnitte",
        "ma_settings": "MA-Einstellungen",
        "ma_period": "Periode",
        "macd": "MACD",
        "macd_settings": "MACD-Einstellungen",
        "macd_fast": "Schnelle Periode",
        "macd_slow": "Langsame Periode",
        "macd_signal": "Signalperiode",
        "rsi": "RSI",
        "rsi_settings": "RSI-Einstellungen",
        "rsi_period": "Periode",
        "ichimoku": "Ichimoku Cloud",
        "ichimoku_settings": "Ichimoku-Einstellungen",
        "ichimoku_tenkan": "Tenkan-Periode",
        "ichimoku_kijun": "Kijun-Periode",
        "ichimoku_senkou": "Senkou-Periode",
        "zoom_in": "Vergrößern",
        "zoom_out": "Verkleinern",
        "update": "Aktualisieren",
        "current_price": "Aktueller Preis",
        "price_change": "Preisänderung",
        "volume": "24h Volumen",
        "market_cap": "Marktkapitalisierung",
        "error_no_data": "Keine Daten verfügbar",
        "support_levels": "Unterstützungsniveaus",
        "resistance_levels": "Widerstandsniveaus",
        "strength": "Stärke",
        "price_label": "Preis",
        "change_label": "Änderung",
        "volume_label": "Volumen",
        "market_cap_label": "Marktkapitalisierung",
        "pan_left": "← Nach Links",
        "pan_right": "Nach Rechts →"
    }
}

def get_texts(language):
    """Get texts based on selected language"""
    if language in texts:
        return texts[language]
    return texts["English"] 