texts_en = {
    "title": "Crypto Chart Pro",
    "subtitle": "Professional Cryptocurrency Analysis Tool",
    "pair": "Trading Pair",
    "timeframe": "Timeframe",
    "indicators": "Technical Indicators",
    "ma": "Moving Averages",
    "ma_count": "Number of MAs",
    "ma_period": "MA-{i} Period",
    "macd": "MACD",
    "macd_fast": "Fast Period",
    "macd_slow": "Slow Period",
    "macd_signal": "Signal Period",
    "ichimoku": "Ichimoku Cloud",
    "tenkan": "Tenkan",
    "kijun": "Kijun",
    "senkou": "Senkou",
    "rsi": "RSI",
    "rsi_period": "RSI Period",
    "update": "Update Chart",
    "price_label": "Price (USDT)",
    "current_price": "Current Price",
    "price_change": "24h Change",
    "volume": "24h Volume",
    "market_cap": "Market Cap",
    "no_data": "No data available.",
    "zoom_in": "Zoom In",
    "zoom_out": "Zoom Out",
    "pan": "Pan Mode",
    "volume_profile": "Volume Profile",
    "order_book": "Order Book",
    "trades": "Recent Trades",
    "settings": "Chart Settings",
    "theme": "Theme",
    "dark": "Dark",
    "light": "Light",
    "grid": "Show Grid",
    "crosshair": "Show Crosshair",
    "timezone": "Timezone",
    "utc": "UTC",
    "local": "Local"
}

texts_fa = {
    "title": "نمودار حرفه‌ای ارزهای دیجیتال",
    "subtitle": "ابزار تحلیل حرفه‌ای ارزهای دیجیتال",
    "pair": "جفت‌ارز",
    "timeframe": "تایم‌فریم",
    "indicators": "اندیکاتورهای تکنیکال",
    "ma": "میانگین‌های متحرک",
    "ma_count": "تعداد میانگین‌های متحرک",
    "ma_period": "دوره MA-{i}",
    "macd": "مکدی",
    "macd_fast": "دوره سریع",
    "macd_slow": "دوره کند",
    "macd_signal": "دوره سیگنال",
    "ichimoku": "ابر ایچیموکو",
    "tenkan": "تنکان",
    "kijun": "کیجون",
    "senkou": "سنکو",
    "rsi": "RSI",
    "rsi_period": "دوره RSI",
    "update": "به‌روزرسانی نمودار",
    "price_label": "قیمت (USDT)",
    "current_price": "قیمت فعلی",
    "price_change": "تغییر ۲۴ ساعت",
    "volume": "حجم معاملات ۲۴ ساعت",
    "market_cap": "ارزش بازار",
    "no_data": "داده‌ای برای نمایش وجود ندارد.",
    "zoom_in": "بزرگ‌نمایی",
    "zoom_out": "کوچک‌نمایی",
    "pan": "حالت جابجایی",
    "volume_profile": "پروفیل حجم",
    "order_book": "دفتر سفارشات",
    "trades": "معاملات اخیر",
    "settings": "تنظیمات نمودار",
    "theme": "تم",
    "dark": "تیره",
    "light": "روشن",
    "grid": "نمایش خطوط شبکه",
    "crosshair": "نمایش خطوط راهنما",
    "timezone": "منطقه زمانی",
    "utc": "UTC",
    "local": "محلی"
}

def get_texts(language):
    return texts_en if language == "English" else texts_fa 