texts_en = {
    "title": "Crypto Chart Pro",
    "subtitle": "Professional Cryptocurrency Analysis Tool",
    "language": "Language",
    "theme": "Theme",
    "dark": "Dark",
    "light": "Light",
    "chart_settings": "Chart Settings",
    "show_grid": "Show Grid",
    "show_crosshair": "Show Crosshair",
    "timezone": "Timezone",
    "select_coin": "Select Cryptocurrency",
    "select_timeframe": "Select Timeframe",
    "indicators": "Technical Indicators",
    "ma": "Moving Averages",
    "ma_settings": "MA Settings",
    "ma_period": "MA Period",
    "macd": "MACD",
    "macd_settings": "MACD Settings",
    "macd_fast": "Fast Period",
    "macd_slow": "Slow Period",
    "macd_signal": "Signal Period",
    "rsi": "RSI",
    "rsi_settings": "RSI Settings",
    "rsi_period": "RSI Period",
    "ichimoku": "Ichimoku Cloud",
    "ichimoku_settings": "Ichimoku Settings",
    "ichimoku_tenkan": "Tenkan Period",
    "ichimoku_kijun": "Kijun Period",
    "ichimoku_senkou": "Senkou Period",
    "current_price": "Current Price",
    "price_change": "24h Change",
    "volume": "24h Volume",
    "market_cap": "Market Cap",
    "price_label": "Price (USDT)",
    "zoom_in": "Zoom In",
    "zoom_out": "Zoom Out",
    "pan": "Pan Mode",
    "error_no_data": "No data available."
}

texts_fa = {
    "title": "نمودار حرفه‌ای ارزهای دیجیتال",
    "subtitle": "ابزار تحلیل حرفه‌ای ارزهای دیجیتال",
    "language": "زبان",
    "theme": "تم",
    "dark": "تیره",
    "light": "روشن",
    "chart_settings": "تنظیمات نمودار",
    "show_grid": "نمایش خطوط شبکه",
    "show_crosshair": "نمایش خطوط راهنما",
    "timezone": "منطقه زمانی",
    "select_coin": "انتخاب ارز دیجیتال",
    "select_timeframe": "انتخاب تایم‌فریم",
    "indicators": "اندیکاتورهای تکنیکال",
    "ma": "میانگین‌های متحرک",
    "ma_settings": "تنظیمات میانگین متحرک",
    "ma_period": "دوره میانگین متحرک",
    "macd": "مکدی",
    "macd_settings": "تنظیمات مکدی",
    "macd_fast": "دوره سریع",
    "macd_slow": "دوره کند",
    "macd_signal": "دوره سیگنال",
    "rsi": "RSI",
    "rsi_settings": "تنظیمات RSI",
    "rsi_period": "دوره RSI",
    "ichimoku": "ابر ایچیموکو",
    "ichimoku_settings": "تنظیمات ایچیموکو",
    "ichimoku_tenkan": "دوره تنکان",
    "ichimoku_kijun": "دوره کیجون",
    "ichimoku_senkou": "دوره سنکو",
    "current_price": "قیمت فعلی",
    "price_change": "تغییر ۲۴ ساعت",
    "volume": "حجم معاملات ۲۴ ساعت",
    "market_cap": "ارزش بازار",
    "price_label": "قیمت (USDT)",
    "zoom_in": "بزرگ‌نمایی",
    "zoom_out": "کوچک‌نمایی",
    "pan": "حالت جابجایی",
    "error_no_data": "داده‌ای برای نمایش وجود ندارد."
}

texts_de = {
    "title": "Crypto Chart Pro",
    "subtitle": "Professionelles Kryptowährungs-Analyse-Tool",
    "language": "Sprache",
    "theme": "Design",
    "dark": "Dunkel",
    "light": "Hell",
    "chart_settings": "Diagramm-Einstellungen",
    "show_grid": "Raster anzeigen",
    "show_crosshair": "Fadenkreuz anzeigen",
    "timezone": "Zeitzone",
    "select_coin": "Kryptowährung auswählen",
    "select_timeframe": "Zeitrahmen auswählen",
    "indicators": "Technische Indikatoren",
    "ma": "Gleitende Durchschnitte",
    "ma_settings": "MA-Einstellungen",
    "ma_period": "MA-Periode",
    "macd": "MACD",
    "macd_settings": "MACD-Einstellungen",
    "macd_fast": "Schnelle Periode",
    "macd_slow": "Langsame Periode",
    "macd_signal": "Signal-Periode",
    "rsi": "RSI",
    "rsi_settings": "RSI-Einstellungen",
    "rsi_period": "RSI-Periode",
    "ichimoku": "Ichimoku Cloud",
    "ichimoku_settings": "Ichimoku-Einstellungen",
    "ichimoku_tenkan": "Tenkan-Periode",
    "ichimoku_kijun": "Kijun-Periode",
    "ichimoku_senkou": "Senkou-Periode",
    "current_price": "Aktueller Preis",
    "price_change": "24h Änderung",
    "volume": "24h Volumen",
    "market_cap": "Marktkapitalisierung",
    "price_label": "Preis (USDT)",
    "zoom_in": "Vergrößern",
    "zoom_out": "Verkleinern",
    "pan": "Verschiebungsmodus",
    "error_no_data": "Keine Daten verfügbar."
}

def get_texts(language):
    """Get texts based on selected language"""
    if language == "English":
        return texts_en
    elif language == "Persian":
        return texts_fa
    elif language == "German":
        return texts_de
    return texts_en 